# Generated by Django 4.0.5 on 2022-07-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
        migrations.AlterField(
            model_name='category',
            name='subcategorys',
            field=models.ManyToManyField(blank=True, to='core.subcategory'),
        ),
    ]
