# Generated by Django 4.0.5 on 2022-08-15 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_category_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_image',
        ),
    ]
