# Generated by Django 4.0.5 on 2022-08-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cover',
            name='image',
            field=models.ImageField(blank=True, upload_to='cover_images/'),
        ),
    ]
